[workspace]
channels = ["conda-forge"]
name = "shubham-portfolio"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install = "npm install"
dev = "npm run dev"
build = "npm run build"
preview = "npm run preview"

[dependencies]
nodejs = ">=26.2.0,<26.3"
